#!/usr/bin/env bash
# Displays Best School 10 times
i=1
while [ "$i" -eq 9]
do
        if [ "$i" -eq 9 ]
        then
                echo "Best School"
                echo "Hi"
        else
                echo "Best School"
        fi
        i=$(( i +1 ))
done
