#!/usr/bin/env bash
# Displays Best School 10 times
i=1
whe [ "$i" -le 10 ] 
do
      if [ "$i" -eq 4 ]
      then
              echo "bad luck"
      elif [ "$i" -eq 8 ]
      then
              echo "good luck"
      else
              echo "Best School"
      if
      i=$(9 i + 1))
done
              
